In [1]:
# Imported modules
using Printf # Needed to use printf
using Statistics

In [2]:
s = 0
s = "Dog"
println(s)

Dog


In [3]:
#function changeNum()
#    x::Int8 = 10
#    x = "Dog"
#end
#changeNum()
# Bool : true or false
canDrive = true

true

In [4]:
bF = 1.111111111111111
println(bF + 0.111111111111111)

1.2222222222222219


In [5]:
c1 = 'A'

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [6]:
# Cast from Int to Char
c2 = Char(120)
println(c2)

x


In [7]:
# Cast from Float to Int
i1 = UInt8(trunc(3.14))
println(i1)

3


In [8]:
# Cast string to Float
f1 = parse(Float64,"1")
println(f1)

1.0


In [9]:
# Cast string to Int
i2 = parse(Int8,"1")
println(i2)

1


In [10]:
s1 = "Just some random words\n"

"Just some random words\n"

In [11]:
# Size of string
println(length(s1))

23


In [12]:
# The 1st index is at 1
println(s1[1])

J


In [13]:
# Get last character
println(s1[end])

In [14]:
# Get a range
println(s1[1:4])

Just


In [15]:
s2 = string("Yukiteru", " Amano")
println(s2)
# And
println("Yuno" * " Gasai")

Yukiteru Amano
Yuno Gasai


In [16]:
s3 = """I
have
many
lines"""
println(s3)

I
have
many
lines


In [17]:
println("Takao" > "Hiyama")

true


In [18]:
println(findfirst(isequal('i'), "Keigo"))

3


In [19]:
println(occursin("key", "monkey"))

true


In [20]:
i3 = 2
i4 = 3
println("$i3 + $i4 = $(i3 + i4)")

2 + 3 = 5


In [21]:
age = 12
if age >= 5 && age <= 6
    println("You're in Kindergarten")
elseif age >= 7 && age <= 13
    println("You're in Middle School")
elseif age >= 14 && age <= 18
    println("You're in High School")
else
    println("Stay Home")
end

You're in Middle School


In [22]:
@printf("true || false = %s\n", true || false ? "true" : "false")
@printf("!true = %s\n", !true ? "true" : "false")

age = 55
@printf("Can I drive : %s\n", age > 16 ? "true" : "false")

true || false = true
!true = false
Can I drive : true


In [23]:
i = 1

while i < 20
    if (i % 2) == 0
        println(i)
        global i += 1
        continue # Skip the rest of the code in the loop
    end

    # Make the code use the global i
    global i += 1

    if i >= 10
        break # Jump out of the loop
    end
end

2
4
6
8


In [24]:
for i = 1:5
    println(i)
end

1
2
3
4
5


In [25]:
# Using an array
for i in [2,4,6]
    println(i)
end

2
4
6


In [26]:
# Loop while iterating multiple variables
# The 2nd value in the j range is the step
for i = 1:5, j = 2:2:10
    println((i, j))
end

(1, 2)
(1, 4)
(1, 6)
(1, 8)
(1, 10)
(2, 2)
(2, 4)
(2, 6)
(2, 8)
(2, 10)
(3, 2)
(3, 4)
(3, 6)
(3, 8)
(3, 10)
(4, 2)
(4, 4)
(4, 6)
(4, 8)
(4, 10)
(5, 2)
(5, 4)
(5, 6)
(5, 8)
(5, 10)


In [27]:
# Create an array of zeros
a1 = zeros(Int32, 2, 2)

2×2 Array{Int32,2}:
 0  0
 0  0

In [28]:
# Create array of Int32s
a2 = Array{Int32}(undef, 5)

5-element Array{Int32,1}:
 234824000
         0
 234824064
         0
 234824128

In [29]:
# Or like this
a3 = Float64[]

0-element Array{Float64,1}

In [30]:
# Create an array
a4 = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [31]:
# Get value at index
println(a4[1])

1


In [32]:
# Get last value
println(a4[end])

3


In [33]:
# Check if value exists
println(5 in a4)

false


In [34]:
# Get 1st index
println(findfirst(isequal(2), a4))

2


In [35]:
f(a) = (a >= 2) ? true : false
println(findall(f, a4))

[2, 3]


In [36]:
# How many items pass the test
println(count(f, a4))

2


In [37]:
# Get row and column size
println(size(a4))

(3,)


In [38]:
# Get number of elements
println(length(a4))

3


In [39]:
# Sum values
println(sum(a4))

6


In [40]:
splice!(a4, 2:1, [8,9])
println(a4)

[1, 8, 9, 2, 3]


In [41]:
splice!(a4, 2:3)
println(a4)

[1, 2, 3]


In [42]:
# Get max & min value
println(maximum(a4))
println(minimum(a4))

3
1


In [43]:
println(a4 * 2)

[2, 4, 6]


In [44]:
a5 = [1,3.14,"Hello"]

3-element Array{Any,1}:
 1       
 3.14    
  "Hello"

In [45]:
# You can store functions

In [46]:
a6 = [sin, cos, tan]
for n in a6
    println(n(0))
end

0.0
1.0
0.0


In [47]:
a7 = [1 2 3; 4 5 6]
for n = 1:2, m = 1:3
    @printf("%d ", a7[n,m])
end
println()

1 2 3 4 5 6 


In [48]:
a11 = [n * m for n in 1:5, m in 1:5]
println(a11)

[1 2 3 4 5; 2 4 6 8 10; 3 6 9 12 15; 4 8 12 16 20; 5 10 15 20 25]


In [49]:
a12 = rand(0:9, 5, 5)
for n = 1:5
    for m = 1:5
        print(a12[n, m])
    end
    println()
end

07514
46744
11244
22867
11772


In [50]:
println(a7[:, 2])

[2, 5]


In [51]:
println(a7[2, :])

[4, 5, 6]


In [52]:
a8 = collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [53]:
a9 = collect(2:2:10)
for n in a9 print(n) end
println()

246810


In [54]:
a10 = [n^2 for n in 1:5]

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [55]:
push!(a10, 36)
println(a10)

[1, 4, 9, 16, 25, 36]


In [56]:
t1 = (1,2,3,4)
println(t1)

(1, 2, 3, 4)


In [57]:
# Get a value
println(t1[1])

1


In [58]:
# Get all
for i in t1
    println(i)
end

1
2
3
4


In [59]:
t2 = ((1,2), (3,4))
println(t2[1][1])

1


In [60]:
t3 = (sue = ("Sue", 100), paul = ("Paul", 23))
println(t3.sue)

("Sue", 100)


In [61]:
d1 = Dict("pi"=>3.14, "e"=>2.718)

Dict{String,Float64} with 2 entries:
  "e"  => 2.718
  "pi" => 3.14

In [62]:
# Get value
println(d1["pi"])

3.14


In [63]:
# Add a kv
d1["golden"] = 1.618

1.618

In [64]:
# Delete a kv
delete!(d1, "pi")

Dict{String,Float64} with 2 entries:
  "golden" => 1.618
  "e"      => 2.718

In [65]:
# Check if key exists
println(haskey(d1, "pi"))

false


In [66]:
# Check for key & value
println(in(("pi"=>3.14)))

Base.Fix2{typeof(in),Pair{String,Float64}}(in, "pi" => 3.14)


In [67]:
# Display all keys
println(keys(d1))

["golden", "e"]


In [68]:
# Display all values
println(values(d1))

[1.618, 2.718]


In [69]:
# Display both
for kv in d1
    println(kv)
end

"golden" => 1.618
"e" => 2.718


In [70]:
# Control display of kv
for(key, value) in d1
    println(key, " : ", value)
end

golden : 1.618
e : 2.718


In [71]:
st1 = Set(["Jim", "Pam", "Jim"])
println(st1)

Set(["Pam", "Jim"])


In [72]:
# Add a value
push!(st1, "Michael")

Set(["Pam", "Jim", "Michael"])

In [73]:
# Check for value
println(in("Dwight", st1))

false


In [74]:
st2 = Set(["Stanley", "Meredith"])
println(union(st1, st2))

Set(["Pam", "Stanley", "Jim", "Michael", "Meredith"])


In [75]:
println(intersect(st1, st2))

Set(String[])


In [76]:
println(setdiff(st1, st2))

Set(["Pam", "Jim", "Michael"])


In [77]:
# This is a single expression function
getSum(x,y) = x + y
x, y = 1, 2
@printf("%d + %d = %d\n", x, y, x+y)

1 + 2 = 3


In [78]:
# You can asign default values
function canIVote(age=16)
    if age > 18
        println("Can Vote")
    else
        println("Can't Vote")
    end
end
canIVote(43)

Can Vote


In [79]:
# Arguments are pass by value
v1 = 5
function changeV1(v1)
    v1 = 10
end
changeV1(v1)
println(v1)

5


In [80]:
# You can use globals inside functions
function changeV12()
    global v1 = 10
end
changeV12()
println(v1)

10


In [81]:
function getSum2(args...)
    sum = 0
    for a in args
        sum += a
    end
    println(sum)
end
getSum2(1,2,3,4)

10


In [82]:
function next2(val)
    return (val + 1, val + 2)
end
println(next2(4))

(5, 6)


In [83]:
function makeMultiplier(num)
    return function (x) return x * num end
end

makeMultiplier (generic function with 1 method)

In [84]:
mult3 = makeMultiplier(3)
println(mult3(6))

18


In [85]:
function getSum3(num1::Number, num2::Number)
    return num1 + num2
end

getSum3 (generic function with 1 method)

In [86]:
function getSum3(num1::String, num2::String)
    return parse(Int32, num1) + parse(Int32, num2)
end

getSum3 (generic function with 2 methods)

In [87]:
f1 = parse(Float64,"1")

1.0

In [88]:
println("5 + 4 = ", getSum3(5,4))
println("5 + 4 = ", getSum3("5","4"))

5 + 4 = 9
5 + 4 = 9


In [89]:
v2 = map(x -> x * x, [1,2,3])
println(v2)

[1, 4, 9]


In [90]:
# Add arrays
v3 = map((x,y) -> x + y, [1,2], [3,4])
println(v3)

[4, 6]


In [91]:
# Reduce uses a function multiple times for 1 result
v4 = reduce(+, 1:100)
println(v4)

5050


In [92]:
# Get longest word in a sentence
sentence = "This is a string"
# Convert string to array
sArray = split(sentence)
longest = reduce((x, y) -> length(x) > length(y) ? x : y, sArray )
println(longest)

string


In [93]:
@printf("5 + 4 = %d\n", (5 + 4))
@printf("5 - 4 = %d\n", (5 - 4))
@printf("5 * 4 = %d\n", (5 * 4))
@printf("5 / 4 = %d\n", (5 / 4))
println("5 % 4 = ", (5 % 4))
@printf("5 ^ 4 = %d\n", (5 ^ 4))

5 + 4 = 9
5 - 4 = 1
5 * 4 = 20
5 / 4 = 1
5 % 4 = 1
5 ^ 4 = 625


In [94]:
@printf("round(3.5) = %d\n", round(3.5))
@printf("floor(3.5) = %d\n", floor(3.5))
@printf("ceil(3.5) = %d\n", round(3.5))
@printf("abs(-3.5) = %d\n", abs(-3.5))
@printf("sqrt(100) = %d\n", sqrt(100))
@printf("cbrt(100) = %d\n", cbrt(100))
@printf("hypot(90,90) = %d\n", hypot(90,90))
@printf("exp(2) = %d\n", exp(2))
@printf("log(100) = %d\n", log(100))
@printf("log2(100) = %d\n", log2(100))
@printf("log10(100) = %d\n", log10(100))

round(3.5) = 4
floor(3.5) = 3
ceil(3.5) = 4
abs(-3.5) = 4
sqrt(100) = 10
cbrt(100) = 5
hypot(90,90) = 127
exp(2) = 7
log(100) = 5
log2(100) = 7
log10(100) = 2


In [95]:
x = 5
println(2x)

10


In [96]:
a13 = [1,2,3]
println(a13 .* 3)

[3, 6, 9]


In [97]:
@enum Color begin
    red = 1
    blue = 2
    green = 3
end

In [98]:
favColor = green::Color
println(favColor)

green


In [99]:
:Derek
println(:Derek)

Derek


In [100]:
d2 = Dict(:pi=>3.14, :e=>2.718)
println(d2[:pi])

3.14


In [101]:
struct Customer
    name::String
    balance::Float32
    id::Int
end

In [102]:
# Create a Customer object
bob = Customer("Bob Smith", 10.50, 123)
println(bob.name)

Bob Smith


In [103]:
abstract type Animal end

In [104]:
struct Dog <: Animal
    name::String
    bark::String
end

In [105]:
struct Cat <: Animal
    name::String
    meow::String
end

In [106]:
bowser = Dog("Bowser", "Ruff")
muffin = Cat("Muffin", "Meow")

Cat("Muffin", "Meow")

In [107]:
function makeSound(animal::Dog)
    println("$(animal.name) says $(animal.bark)")
end

makeSound (generic function with 1 method)

In [108]:
function makeSound(animal::Cat)
    println("$(animal.name) says $(animal.meow)")
end

makeSound (generic function with 2 methods)

In [109]:
makeSound(bowser)
makeSound(muffin)

Bowser says Ruff
Muffin says Meow


In [110]:
print("Enter a number ")
num1 = chomp(readline())

Enter a number stdin> 5


"5"

In [111]:
print("Enter a number ")
num2 = chomp(readline())

Enter a number stdin> 8


"8"

In [112]:
try
    val = (parse(Int32, num1)) / (parse(Int32, num2))
    if (val == Inf)
        error("Can't divide by zero")
    else
        println(val)
    end
catch e
    println(e)
end

0.625


In [113]:
# Open file for writing
open("random.txt", "w") do file
    write(file, "Here is some random text\nIt is great\n")
end

37

In [114]:
# Open a file for reading
open("random.txt") do file
    # Read whole file into a string
    data = read(file, String)
    println(data)
end

Here is some random text
It is great



In [115]:
open("random.txt") do file
    # Read each line 1 at a time
    for line in eachline(file)
        println(line)
    end
end

Here is some random text
It is great


In [116]:
macro doMore(n, exp)
  quote

      # esc hides what it contains until everything
      # is ready to be executed
    for i = 1:$(esc(n))
      $(esc(exp))
    end
  end
end

@doMore (macro with 1 method)

In [117]:
@doMore(2, println("Hello"))

Hello
Hello


In [118]:
macro doWhile(exp)
    # Assert that while is the first element passed
  @assert exp.head == :while

  # quote is the same as begin ... end
  esc(quote

  # Contains the body of the loop
    $(exp.args[2])
    $exp
  end)
end

@doWhile (macro with 1 method)

In [119]:
z = 0
@doWhile while z < 10
    global z += 1
    println(z)
end

1
2
3
4
5
6
7
8
9
10


###### 